# Serverless Config
service: api-todo
frameworkVersion: '2'

#Provider
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  lambdaHashingVersion: 20201221
  stage: dev

  # #Custom
  # custom:
  #   defaultStage: dev
  #   currentStage: ${opt:stage, self:custom.defaultStage}

  # Environment Variables
  environment:
    DYNAMODB_TABLE: todo-api-table

  #IAM Roles  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

#Lambda
functions:
  create:
    handler: create.create
    events: 
      - http:
          path: /addItem
          method: post

  list:
    handler: list.list
    events: 
      - http:
          path: /list
          method: get

resources:
  Resources:
    TodosDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1